using System;

namespace OpenSettings.Helpers
{
    internal static class RowVersionHelper
    {
        /// <summary>
        /// Converts the given <see cref="DateTime"/> to a byte array representing the row version.
        /// The byte array is generated by converting the <see cref="DateTime.Ticks"/> property to a byte array.
        /// </summary>
        /// <param name="dateTime">The <see cref="DateTime"/> to convert to a row version.</param>
        /// <returns>A byte array representing the row version based on the <see cref="DateTime.Ticks"/>.</returns>
        public static byte[] Date(DateTime dateTime)
        {
            return BitConverter.GetBytes(dateTime.Ticks);
        }

        public static byte[] Random()
        {
            return Guid.NewGuid().ToByteArray();
        }
    }
}