using Ogu.Compressions.Abstractions;
using OpenSettings.Models;
using System;
using System.IO.Compression;

namespace OpenSettings.Domains.Sql.Entities
{
    public class GlobalConfigurationHistorySqlModel : EntityBase<Guid>
    {
        /// <summary>
        /// The key of the global configuration history.
        /// </summary>
        public string Key { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Key"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string KeyLowercase { get; set; }

        /// <summary>
        /// The binary data associated with the global configuration history.
        /// </summary>
        public byte[] Data { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// The associated client id with this global configuration history if any.
        /// </summary>
        public Guid? ClientId { get; set; }

        /// <summary>
        /// The identifier associated with this global configuration history if any.
        /// </summary>
        public Guid? IdentifierId { get; set; }

        /// <summary>
        /// Defines the serialization type used for data serialization and deserialization.
        /// </summary>
        public SerializerType SerializerType { get; set; }

        /// <summary>
        /// Specifies the type of compression applied to the data.  
        /// Determines which decoding method should be used.
        /// </summary>
        public CompressionType CompressionType { get; set; }

        /// <summary>
        /// Defines the level of compression used.
        /// </summary>
        public CompressionLevel CompressionLevel { get; set; }

        /// <summary>
        /// Represents the version of the global configuration history.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// An url friendly version of the <see cref="Version"/>, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The date and time when the entity was last restored, or <c>null</c> if never restored.
        /// </summary>
        public DateTime? RestoredOn { get; set; }

        /// <summary>
        /// A concurrency token used for tracking changes.  
        /// Helps prevent conflicts during concurrent updates.
        /// </summary>
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        public Guid? TenantId { get; set; }

        public virtual TenantSqlModel Tenant { get; set; }

        /// <summary>
        /// The global configuration id associated with this global configuration history.
        /// </summary>
        public Guid GlobalConfigurationId { get; set; }

        public virtual GlobalConfigurationSqlModel GlobalConfiguration { get; set; }

        /// <summary>
        /// The id of the user who created this global configuration history.
        /// </summary>
        public Guid? CreatedById { get; set; }

        /// <summary>
        /// The user who created this global configuration history.
        /// </summary>
        public virtual UserSqlModel CreatedBy { get; set; }

        /// <summary>
        /// The id of the user who last restored this global configuration history.
        /// </summary>
        public Guid? RestoredById { get; set; }

        /// <summary>
        /// The user who last restored this global configuration history.
        /// </summary>
        public virtual UserSqlModel RestoredBy { get; set; }
    }
}