using System;
using System.Collections.Generic;

namespace OpenSettings.Domains.Sql.Entities
{
    /// <summary>
    /// Represents a user-claim entity.
    /// </summary>
    public class UserClaimSqlModel : EntityBase<Guid>
    {
        /// <summary>
        /// The claim type.
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Type"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string TypeLowercase { get; set; }

        /// <summary>
        /// The claim value.
        /// </summary>
        public string Value { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Value"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string ValueLowercase { get; set; }

        /// <summary>
        /// An url friendly version of the ?, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The description of the claim.
        /// </summary>
        public string Description { get; set; }

        public Guid? TenantId { get; set; }

        public virtual TenantSqlModel Tenant { get; set; }

        /// <summary>
        /// The collection of user group-claim mappings assigned to the user claim.
        /// </summary>
        public virtual ICollection<UserGroupUserClaimMappingSqlModel> UserGroupUserClaimMappings { get; set; } = new List<UserGroupUserClaimMappingSqlModel>();

        /// <summary>
        /// The collection of user role-claim mappings assigned to the user claim.
        /// </summary>
        public virtual ICollection<UserRoleUserClaimMappingSqlModel> UserRoleUserClaimMappings { get; set; } = new List<UserRoleUserClaimMappingSqlModel>();

        /// <summary>
        /// The collection of user-claim mappings assigned to the user claim.
        /// </summary>
        public virtual ICollection<UserClaimMappingSqlModel> UserClaimMappings { get; set; } = new List<UserClaimMappingSqlModel>();
    }
}