using OpenSettings.Helpers;
using OpenSettings.Models;
using System;
using System.Collections.Generic;

namespace OpenSettings.Domains.Sql.Entities
{
    /// <summary>
    /// Represents a user entity.
    /// </summary>
    public class UserSqlModel : EntityBase<Guid>
    {
        /// <summary>
        /// The authentication type used by the user (e.g., "Machine", "OpenIdConnect").
        /// </summary>
        public AuthType AuthType { get; set; }

        /// <summary>
        /// The identity provider name (e.g., "local", Google", "Facebook") if the user authenticated using external service.
        /// </summary>
        public string IdentityProvider { get; set; }

        /// <summary>
        /// The unique identifier provided by the identity provider if any.
        /// </summary>
        public string ExternalId { get; set; }

        /// <summary>
        /// The user's email address.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Email"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string EmailLowercase { get; set; }

        /// <summary>
        /// The username of the user.
        /// </summary>
        public string Username { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Username"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string UsernameLowercase { get; set; }

        /// <summary>
        /// The hashed password for authentication.
        /// </summary>
        public string HashedPassword { get; set; }

        /// <summary>
        /// The given name of the user. 
        /// </summary>
        public string GivenName { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="GivenName"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string GivenNameLowercase { get; set; }

        public string MiddleName { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="MiddleName"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string MiddleNameLowercase { get; set; }

        /// <summary>
        /// The family name 
        /// </summary>
        public string FamilyName { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="FamilyName"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string FamilyNameLowercase { get; set; }

        /// <summary>
        /// The full name of the user.
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="FullName"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string FullNameLowercase { get; set; }

        /// <summary>
        /// An url friendly version of the user, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The display name of the user, which may be different from their username or full name.
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// The user's initials, typically derived from their name.
        /// (using <see cref="Helper.GetInitials"/> helper method)
        /// </summary>
        public string Initials { get; set; }

        public string PictureUrl { get; set; }

        public string Locale { get; set; }

        /// <summary>
        /// The date and time when the user last logged in.
        /// </summary>
        public DateTime LastLogin { get; set; }

        public bool IsEmailVerified { get; set; }

        /// <summary>
        /// Indicates whether the user account is active.
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// A concurrency token used for tracking changes.  
        /// Helps prevent conflicts during concurrent updates.
        /// </summary>
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// The collection of user-notification mappings associated with the user.
        /// </summary>
        public virtual ICollection<UserNotificationMappingSqlModel> UserNotificationMappings { get; set; } = new List<UserNotificationMappingSqlModel>();

        /// <summary>
        /// The collection of user-group mappings assigned to the user.
        /// </summary>
        public virtual ICollection<UserGroupMappingSqlModel> UserGroupMappings { get; set; } = new List<UserGroupMappingSqlModel>();

        /// <summary>
        /// The collection of user-claim mappings assigned to the user.
        /// </summary>
        public virtual ICollection<UserClaimMappingSqlModel> UserClaimMappings { get; set; } = new List<UserClaimMappingSqlModel>();

        /// <summary>
        /// The collection of user-role mappings assigned to the user.
        /// </summary>
        public virtual ICollection<UserRoleMappingSqlModel> UserRoleMappings { get; set; } = new List<UserRoleMappingSqlModel>();
    }
}