using System;
using System.Collections.Generic;

namespace OpenSettings.Domains.Sql.Entities
{
    /// <summary>
    /// Represents a user group entity.
    /// </summary>
    public class UserGroupSqlModel : EntityBase<Guid>
    {
        /// <summary>
        /// The name of the user group.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Name"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string NameLowercase { get; set; }

        /// <summary>
        /// An url friendly version of the <see cref="Name"/>, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        public Guid? TenantId { get; set; }

        public virtual TenantSqlModel Tenant { get; set; }

        /// <summary>
        /// The collection of user group-claim mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserGroupUserClaimMappingSqlModel> UserGroupUserClaimMappings { get; set; } = new List<UserGroupUserClaimMappingSqlModel>();

        /// <summary>
        /// The collection of user role-group mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserRoleUserGroupMappingSqlModel> UserRoleUserGroupMappings { get; set; } = new List<UserRoleUserGroupMappingSqlModel>();

        /// <summary>
        /// The collection of user-group mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserGroupMappingSqlModel> UserGroupMappings { get; set; } = new List<UserGroupMappingSqlModel>();

        /// <summary>
        /// The collection of user group-notification mappings associated with this notification.
        /// </summary>
        public virtual ICollection<UserGroupNotificationMappingSqlModel> UserGroupNotificationMappings { get; set; } = new List<UserGroupNotificationMappingSqlModel>();
    }
}