using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenSettings.Domains.Sql.Entities
{
    /// <summary>
    /// Represents a user group entity.
    /// </summary>
    [Table("UserGroups")]
    public class UserGroupSqlModel : EntityBase<int>
    {
        /// <summary>
        /// The name of the user group.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Name"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string NameLowercase { get; set; }

        /// <summary>
        /// An url friendly version of the <see cref="Name"/>, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The collection of user group-claim mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserGroupClaimMappingModel> GroupClaimMappings { get; set; } = new List<UserGroupClaimMappingModel>();

        /// <summary>
        /// The collection of user role-group mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserRoleGroupMappingModel> RoleGroupMappings { get; set; } = new List<UserRoleGroupMappingModel>();

        /// <summary>
        /// The collection of user-group mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserGroupMappingSqlModel> UserGroupMappings { get; set; } = new List<UserGroupMappingSqlModel>();

        /// <summary>
        /// The collection of user group-notification mappings assigned to the user group.
        /// </summary>
        public virtual ICollection<UserGroupNotificationMappingSqlModel> GroupNotificationMappings { get; set; } = new List<UserGroupNotificationMappingSqlModel>();
    }
}