using System.Collections.Generic;

namespace OpenSettings.Domains.Sql.Entities
{
    /// <summary>
    /// Represents a user role entity.
    /// </summary>
    public class UserRoleSqlModel : EntityBase<int>
    {
        /// <summary>
        /// The name of the user role.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The lowercase version of the <see cref="Name"/>, typically used for case-insensitive comparisons.
        /// </summary>
        public string NameLowercase { get; set; }

        /// <summary>
        /// An url friendly version of the <see cref="Name"/>, generated by trimming, converting to lowercase,  
        /// and replacing spaces or special characters with hyphens (using <see cref="Extensions.InternalExtensions.ToSlug"/> extension method).
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The collection of user role-claim mappings associated with this user role.
        /// </summary>
        public virtual ICollection<UserRoleUserClaimMappingSqlModel> UserRoleUserClaimMappings { get; set; } = new List<UserRoleUserClaimMappingSqlModel>();

        /// <summary>
        /// The collection of user-role mappings associated with this user role.
        /// </summary>
        public virtual ICollection<UserRoleMappingSqlModel> UserRoleMappings { get; set; } = new List<UserRoleMappingSqlModel>();

        /// <summary>
        /// The collection of role-group mappings associated with this user role.
        /// </summary>
        public virtual ICollection<UserRoleUserGroupMappingSqlModel> UserRoleUserGroupMappings { get; set; } = new List<UserRoleUserGroupMappingSqlModel>();
    }
}