<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
	<AssemblyOriginatorKeyFile>OpenSettings.AspNetCore.Tests.snk</AssemblyOriginatorKeyFile>
	<SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenSettings.AspNetCore\OpenSettings.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="OpenSettings.AspNetCore.Tests.snk" Visible="false" />
    <None Include="OpenSettings.AspNetCore.Tests.publickey" Visible="false" />
  </ItemGroup>

</Project>
