<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<AssemblyName>OpenSettings</AssemblyName>
		<PackageId>OpenSettings</PackageId>
		<Product>OpenSettings</Product>
		<Authors>OpenSettings</Authors>
		<Copyright>Copyright (c) OpenSettings 2024</Copyright>
		<PackageProjectUrl>https://github.com/OpenSettings/open-settings</PackageProjectUrl>
		<RepositoryUrl>https://github.com/OpenSettings/open-settings</RepositoryUrl>
		<PackageTags>opensettings;dotnet;csharp;configuration;settings;library</PackageTags>
		<RepositoryType>git</RepositoryType>
		<Description>OpenSettings is a .NET library for managing application settings efficiently.</Description>
		<PackageIcon>open-settings-logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<NeutralLanguage>en</NeutralLanguage>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
		<AssemblyOriginatorKeyFile>OpenSettings.snk</AssemblyOriginatorKeyFile>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.0.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.7.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.36.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.36.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.36.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.36.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net5.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.36.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.36.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="5.7.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.7.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="5.7.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.7.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="5.7.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.7.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="3.1.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.0" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="2.1.0" />
		<PackageReference Include="Ogu.Compressions" Version="2.1.1" />
		<PackageReference Include="Ogu.Extensions.Hosting.HostedServices" Version="2.0.6" />
		<PackageReference Include="Ogu.Response" Version="3.0.9" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.24" />
		<PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="OpenSettings.AspNetCore, PublicKey=0024000004800000940000000602000000240000525341310004000001000100093d0ef22e355dc8add31c3034c7a769867d054575f99cea5166718935138d059f5528b1f1bc31e1dd5ec9cc22c932dd0a034d095a4fbe0339bb6707ca871f0455f75a2ce8b3496183b06c00eced0dbb1a4d77024aa7f5bc66906e3f98591e1a0726b9a010b9b090ad0a8785a5467e4ff205d17cc45e3a46ec3a5a50cbe87a96" />
		<InternalsVisibleTo Include="OpenSettings.AspNetCore.Spa, PublicKey=0024000004800000940000000602000000240000525341310004000001000100c9494213288348583fa1af386bc6a04926141acd766a7b6b3635441f7b6f1ed63398b35f87a9a4bbe8c2df74e10fcb7e2e252cd7799ee38b171412725bb88b0abfc0c44e2598833c1e16f2777bd88855724d9614660eafba47f50b82a1154612262aae5021cc93d14e4b6dc1a39ee258026ad1a9fc64660fc51ef53fed6c74a7" />
		<InternalsVisibleTo Include="OpenSettings.AspNetCore.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001009ddd5bd4c30d442c5c0c220fce4be51b161527fae02dc556dfac5b7620937d6faceb9c902d8412512b61ace006714d9652295725cde5084a4766feea12c2482faf4736e9088f20ee1659501cd28cf7c76dbde4d745b2380e151a6d508592be2ab39c9fff55b47a9c48e5efd1a4f49a6db6c48649e3380f129a87515eb30634ce" />
		<InternalsVisibleTo Include="OpenSettings.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001003d49dc1c44add446374738b46c26270df47489795c0a555312116268101df8ce17b0c10f44641c5671bb2043d66204a328f67b9c554869ae43489b156b2c0023d35836e5d990b9ac6070891c663a041d13deaa717d4050616ab6164755b8b33135e357456ffdbacc944d4e49eb7f3dd65bfa41a60703f66aba08876d24861e9c" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\logo\open-settings-logo.png" Pack="true" PackagePath="\" Visible="false" />
		<None Include="README.md" Pack="true" PackagePath="\" Visible="false" />
		<None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" Visible="false" />
		<None Include="OpenSettings.snk" Visible="false" />
	</ItemGroup>

</Project>