<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<AssemblyName>OpenSettings.AspNetCore.Spa</AssemblyName>
		<PackageId>OpenSettings.AspNetCore.Spa</PackageId>
		<Product>OpenSettings.AspNetCore.Spa</Product>
		<Authors>OpenSettings</Authors>
		<Copyright>Copyright (c) OpenSettings 2024</Copyright>
		<PackageProjectUrl>https://github.com/OpenSettings/open-settings</PackageProjectUrl>
		<RepositoryUrl>https://github.com/OpenSettings/open-settings</RepositoryUrl>
		<PackageTags>opensettings;dotnet;csharp;configuration;settings;library</PackageTags>
		<RepositoryType>git</RepositoryType>
		<Description>OpenSettings.AspNetCore.Spa extends OpenSettings for Single Page Applications (Spa), offering a UI-based settings management solution.</Description>
		<PackageIcon>open-settings-logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<NeutralLanguage>en</NeutralLanguage>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
		<AssemblyOriginatorKeyFile>OpenSettings.AspNetCore.Spa.snk</AssemblyOriginatorKeyFile>
		<SignAssembly>true</SignAssembly>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1'">
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netstandard2.1' Or '$(TargetFramework)' == 'netcoreapp3.1'">
		<PackageReference Include="System.Text.Json" Version="6.0.10" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="open-settings-spa-dist\browser\**\*" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="open-settings-spa-dist\browser\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0' And '$(TargetFramework)' != 'netstandard2.1'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<Target Name="BuildSpa" BeforeTargets="DispatchToInnerBuilds" Condition="'$(Configuration)' == 'Debug'">
		<Exec Command="npm --version" ContinueOnError="true">
			<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
		</Exec>
		<Error Condition="'$(ErrorCode)' != '0'" Text="Node.js/npm is required to build this project." />
		<!--<Exec Command="build-spa-$(Configuration).sh" />-->
	</Target>

	<ItemGroup>
		<None Include="build-spa-Debug.sh" Visible="false" />
		<None Include="build-spa-Release.sh" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="OpenSettings.AspNetCore, PublicKey=0024000004800000940000000602000000240000525341310004000001000100093d0ef22e355dc8add31c3034c7a769867d054575f99cea5166718935138d059f5528b1f1bc31e1dd5ec9cc22c932dd0a034d095a4fbe0339bb6707ca871f0455f75a2ce8b3496183b06c00eced0dbb1a4d77024aa7f5bc66906e3f98591e1a0726b9a010b9b090ad0a8785a5467e4ff205d17cc45e3a46ec3a5a50cbe87a96" />
		<InternalsVisibleTo Include="OpenSettings.AspNetCore.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001009ddd5bd4c30d442c5c0c220fce4be51b161527fae02dc556dfac5b7620937d6faceb9c902d8412512b61ace006714d9652295725cde5084a4766feea12c2482faf4736e9088f20ee1659501cd28cf7c76dbde4d745b2380e151a6d508592be2ab39c9fff55b47a9c48e5efd1a4f49a6db6c48649e3380f129a87515eb30634ce" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\logo\open-settings-logo.png" Pack="true" PackagePath="\" Visible="false" />
		<None Include="README.md" Pack="true" PackagePath="\" Visible="false" />
		<None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" Visible="false" />
        <None Include="OpenSettings.AspNetCore.Spa.snk" Visible="false" />
		<None Include="OpenSettings.AspNetCore.Spa.publickey" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OpenSettings\OpenSettings.csproj" />
	</ItemGroup>

</Project>